#!/bin/bash
cmake -Bbuild -H. -G "Ninja" ${CMAKE_ARGS} -DCMAKE_FIND_ROOT_PATH:PATH=${PREFIX} -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DBUILD_SHARED_LIBS=ON
cmake --build build --target install
