{% set name = "tinycbor" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/tinycbor/archive/v{{ version }}.tar.gz
  sha256: 512e2c9fce74f60ef9ed3af59161e905f9e19f30a52e433fc55f39f4c70d27e4
  patches:
    - 0001-Add-CMake-support.patch
    - 0002-Fix-static_assert-compiler-support.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage( name|lower, max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja

test:
  commands:
    - test -f ${PREFIX}/lib/libtinycbor${SHLIB_EXT}                # [unix]
    - test -f ${PREFIX}/lib/cmake/tinycbor/tinycbor-targets.cmake  # [unix]
    - test -f ${PREFIX}/include/cbor.h                             # [unix]
    - test -f ${PREFIX}/include/tinycbor-version.h                 # [unix]
    - test -f ${PREFIX}/include/tinycbor-export.h                  # [unix]
    - if not exist %LIBRARY_BIN%\tinycbor.dll exit 1                           # [win]
    - if not exist %LIBRARY_LIB%\tinycbor.lib exit 1                           # [win]
    - if not exist %LIBRARY_LIB%\cmake\tinycbor\tinycbor-targets.cmake exit 1  # [win]
    - if not exist %LIBRARY_INC%\cbor.h exit 1                                 # [win]
    - if not exist %LIBRARY_INC%\tinycbor-version.h exit 1                     # [win]
    - if not exist %LIBRARY_INC%\tinycbor-export.h exit 1                      # [win]

about:
  home: https://github.com/intel/tinycbor
  summary: 'Concise Binary Object Representation (CBOR) Library'
  description: |
    The TinyCBOR library is a small CBOR encoder and decoder library, optimized for very fast
    operation with very small footprint. The main encoder and decoder functions do not allocate memory.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://intel.github.io/tinycbor/current/
  dev_url: https://github.com/intel/tinycbor

extra:
  recipe-maintainers:
    - sdebionne
